root = "."
tmp_dir = "tmp"

[build]
cmd = "docker build -t cloud-functions . && docker run --rm -p 3000:3000 cloud-functions"
bin = ""
full_bin = ""
include_ext = ["go", "tpl", "tmpl", "html", "env", "Dockerfile"]
exclude_dir = ["assets", "tmp", "vendor"]
include_dir = []
exclude_file = []
exclude_regex = ["_test\\.go"]
exclude_unchanged = true
follow_symlink = true
log = "air.log"
delay = 1000 # ms
stop_on_error = true
send_interrupt = false
kill_delay = 500 # ms

[log]
time = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true
