spin_manifest_version = "1"
authors = ["josh"]
description = "Get my soundcloud new music stream"
name = "get-sc-stream"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[variables]
sc_oauth_token = { required = true }
sc_client_id = { required = true }

[[component]]
id = "get-sc-stream"
source = "target/get-sc-stream.wasm"
exclude_files = ["**/node_modules"]
allowed_http_hosts = ["insecure:allow-all"]
[component.trigger]
route = "/scstream"
[component.build]
command = "npm run build"
watch = ["src/**/*"]
[component.config]
sc_token = "{{ sc_oauth_token }}"
sc_client_id = "{{ sc_client_id }}"
